from tkinter import*
import random
def MakeNumer():
    global number
    for i in range(4):
        x=random.randrange(0,10)
        number.append(x)
    if number[0]==0:
        number.clear()
        MakeNumer()
    if(len(number)>len(set(number))):
        number.clear()
        MakeNumer()
def click2():
    MakeNumer()
    root=Tk()
    root.title("COWS AND BULLS")
    root.state('zoomed')
    root.config(background='light blue')
    l8=Label(root,bg="light blue",fg="black",bd=5,text="Player Name : "+e1.get()+" "+e2.get(),font=15)
    l8.pack()
    choice1=Label(root,bg="light blue",fg="black",bd=5,text="Please enter 4 distinct number in the below box:",font=15)
    choice1.pack()
    choice=Entry(root,width=20)
    choice.pack()
    scroll_bar = Scrollbar(root)
    scroll_bar.pack( side = RIGHT,fill = Y )
    mylist = Listbox(root,borderwidth=0, highlightthickness=0,bg="light pink",width=50,height=15,fg="white",font=("Times",14,'bold'), yscrollcommand = scroll_bar.set )
    mylist.pack()
    scroll_bar.config( command = mylist.yview )
    def clicked():
        global number
        q=str(number[0])
        r=str(number[1])
        s=str(number[2])
        t=str(number[3])
        choice100=Label(root,text=q+r+s+t,font=12)
        choice100.pack()
        bint=Label(root,bg="light blue",fg="blue4",text="Better Luck next time",font=("Helvetica",20,'bold'))
        bint.pack()
    def click():
        global cows
        global bulls
        global attempts
        global number
        if len(choice.get())>len(set(choice.get())):
            choice2.config(text="Please enter DISTINCT 4 digit number")
            choice.delete(0,END)
        elif len(choice.get())!=4:
            choice2.config(text="Please enter 4 digit number")
            choice.delete(0,END)
        else:
            def PlayGame():
                global cows
                global bulls
                global attempts
                global number
                choice2.config(text="")
                m1=choice.get()
                choice.delete(0,END)
                attempts+=1
                for i in range(4):
                    for j in range(4):
                        if(m1[i]!=str(number[i])):
                            if i!=j:
                                if(m1[i]==str(number[j])):
                                    bulls+=1
                for x in range(4):
                        if(m1[x]==str(number[x])):
                            cows+=1
                if cows!=4:
                    m15="  Entered number: "+m1+"   Cows: "+str(cows)+"  Bulls: "+str(bulls)
                    mylist.insert(0, m15+"\n")
                    #l15=Label(root,text=m15,bg="light blue",fg="black",font =12)
                    #l15.pack()
                elif (cows==4):
                    m15="  Entered number: "+m1+"   Cows: "+str(cows)+"  Bulls: "+str(bulls)
                    mylist.insert(0, m15+"\n")
                    l16=Label(root,text="You win after "+str(attempts)+" attempts!",bg="light blue",fg="blue4",font =("Helvetica",20,"bold"))
                    l16.pack()
            PlayGame()
            cows=0
            bulls=0
    choice2=Label(root,bg="light blue",fg="red",bd=5,text="",font=15)
    choice2.pack()
    b=Button(root,text="Check",command=click,bg="light grey",fg="black",font=("bold",15))
    b.pack()
    bn=Button(root,text="Quit",command=clicked,bg="light grey",fg="black",font=15)
    bn.pack()
def click1():
    root=Tk()
    root.title("COWS AND BULLS")
    root.state('zoomed')
    root.config(background='light salmon')
    l22=Label(root,bg="light salmon",fg="black",text="Hello "+e1.get()+" "+e2.get(),font=15)
    l22.pack()
    l6=Label(root,bg="light salmon",fg="black",bd=5,text="ABOUT THE GAME:",font=15)
    l6.pack()
    l7=Label(root,bg="light salmon",fg="black",bd=5,wraplength=800,text="A random 4 digit number is generated by the computer.Your task is the guess this number.Every correct number guessed in its right digit place gets a COW and every correct number guessed in its wrong digit place gets a BULL.The game ends when the player gets 4 cows i.e, all number guessed are at its right digit place.\n\n\nAll The Best!!",font=15)
    l7.pack()
    b2=Button(root,text="Lets Start!",command=click2,bg="light grey",fg="black",font=("bold",15))
    b2.pack()
    b3=Button(root,text="Quit!",command=root.destroy,bg="light grey",fg="black",font=("bold",15))
    b3.pack()

cows=0
bulls=0
attempts=0
number=[]
root=Tk()
root.title("COWS AND BULLS")
root.state('zoomed')
root.config(background='light blue')
l1=Label(root,bg="grey",fg="white",bd=5,text="First Name:",font=("Times",12,'bold'))
l1.pack()
e1=Entry(root,width=50)
e1.pack()
l2=Label(root,bg="grey",fg="white",bd=5,text="Last Name:",font=("Times",12,'bold'))
l2.pack()
e2=Entry(root,width=50)
e2.pack()
b1=Button(root,text="Click me to begin",command=click1,bg="white",fg="midnight blue",font=("Helvetica",16,"bold"))
b1.pack()
